import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/ui/Header";
import { FormProvider } from "@/providers/FormProvider";


// フォントの設定
const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// フォントの設定
const geistMono = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// メタデータ設定
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <FormProvider>
          {children}
        </FormProvider>
      </body>
    </html>
  );
}
